//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBRGR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int InvitationID { get; set; }
        public System.DateTime MeetDate { get; set; }
        public Nullable<System.TimeSpan> MeetTime { get; set; }
        public int ReceiptID { get; set; }
        public int ClientID { get; set; }
        public int CandidateID { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Client Client { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
